### ISSUE TITLE
EIN with fiscal sponsor

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#103]
Even if a fiscally-sponsored applicant has its own EIN, the application requires it to submit the EIN of its fiscal sponsor as well. 

Need to modify this language in the application:
“If your organization does not have an EIN and is submitting with a fiscal sponsor, provide the fiscal sponsor's EIN”

**Comment by derekwmiller** [comment]
modify to what? @WendyKoelfgen

**Comment by derekwmiller** [comment]
closing due to no response. If edits / mods are still needed, please reopen and message

**Comment by derekwmiller** [comment]
still need clarification
