### ISSUE TITLE
Report for technical review distribution

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#104]
I need an excel with the fields below in order to assign apps for technical review

Passed eligibility screening
Applicant ID
1.1 Organization Name
1.8 Amount of grant request
1.13 Does the project being planned include any physical improvements (e.g. tree / garden / farm, efficiency retrofits, solar / other renewable installations)?
3.1 Type of project

**Comment by derekwmiller** [comment]
@CadyLister where is project type for planning grants? it's not section 3.1

**Comment by derekwmiller** [comment]
done
