### ISSUE TITLE
Can't complete tech review/move to scoring #1299

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#106]
I am getting the same error message when I complete a technical review and try to move on to scoring. This happens when I enter a score and then hit the save button. In this case I was trying to enter a score for criteria 3 and then save. This is a large grant with a single site construction budget less than $500K same as last time.

**Comment by derekwmiller** [comment]
same error as what?

**Comment by derekwmiller** [comment]
@WendyKoelfgen I'm closing this. No response.
