### ISSUE TITLE
confirmation email 

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#11]
need text

**Comment by WendyKoelfgen** [comment]
question - can any of the text be dynamic like this -

Your PCEF ___________ (Large/Small/Planning) grant application was submitted on mm/dd/yyyy at <time>.

**Comment by WendyKoelfgen** [comment]
Just waiting for Sam's approval on the language. Will get it to you as soon as he responds.

**Comment by WendyKoelfgen** [comment]
Sent in email
