### ISSUE TITLE
Technical review not saving

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#111]
Application #1278, i filled out all fields in technical review and hit save, then went to section 6 to double check something and my technical review did not save. This is a large grant

**Comment by derekwmiller** [comment]
there's no tech record for that grant. any more info on what happened?

**Comment by derekwmiller** [comment]
@CadyLister  1278 is a small grant that hasn't been submitted. could that be the issue?

**Comment by CadyLister** [comment]
Sorry, 1287, fat fingers
