### ISSUE TITLE
Scoring not saving

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#112]
Application #1270, this is a large grant that i had entered, saved and submitted the tech review for previously so that info was in there. I entered a value in criterion 3 (one of the staff scored criterion), hit save and then clicked on section 7 and then back to the scoring section and the value in criterion 3 was gone.

**Comment by derekwmiller** [comment]
@CadyLister is this the 'real' score or the technical score?

**Comment by CadyLister** [comment]
@derekwmiller real score

**Comment by derekwmiller** [comment]
it's saving, just not 're-populating' the form

**Comment by derekwmiller** [comment]
will be fixed shortly.

**Comment by CadyLister** [comment]
thanks
