### ISSUE TITLE
Application 1328 wont save edits to tech review comments

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#115]
Application #1328 wont save my notes that go with the tech review, this is one where I think you were testing and there was nonsense text in the comments boxes for eligibility and tech review and the wrong type of project selected. I was able to correct the type of project and save edits to the comments connected to eligibility but the edits I make to the tech review comments box keep disappearing, both when I hit save and also when I hit submit.

**Comment by CadyLister** [comment]
1270 same thing

**Comment by derekwmiller** [comment]
i see tech review notes when I view that record. i did have a test comment / review on that record. could have been the case that my test review, which was marked as submitted, was causing issues. I can't recreate so I'm going to close. If it comes up again go ahead and reopen this or create a new issue.
