### ISSUE TITLE
Final score matrix and method

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#120]
https://portlandoregongov-my.sharepoint.com/:x:/g/personal/cady_lister_portlandoregon_gov/EecBwn1ThGxNjE9JHmMMIHABlLWPB7Ay3ZkTTYjJY6UBZQ?e=ttHSwR

**Comment by derekwmiller** [comment]
use @CadyLister 's spreadsheet (above) to calculate final scores for each application based off project type

**Comment by derekwmiller** [comment]
due 1/29
sneak peak by 1/22
