### ISSUE TITLE
Average scores needed per criteria for each application for applicant feedback

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#121]
Need to be able to grab average scores per criteria for each application. These will be gathered by staff to be sent to applicant for them to provide feedback. We need to send to applicants on January 11th. Deadline for independent review is Jan 7th so staff need to do this work and prep communication on Jan 8th (Friday).

**Comment by derekwmiller** [comment]
@CadyLister @WendyKoelfgen do you need the applicant info for these as well?

**Comment by CadyLister** [comment]
I don't think so as long as we have the application ID then we connect to the combo report. The first thing we will be using this for is to paste the average scores for each criteria for each application into a table to send to the applicant to give them an opportunity to respond.
