### ISSUE TITLE
Scoring panel meeting report

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#122]
For each scoring panel we need to display: criterion ID, reviewer 1 scores, reviewer 2 scores, reviewer 3 scores, average of reviewers 1,2,3 scores. Ideally we would like to highlight criteria rows where there is a 2 or more point difference difference between reviewer scores and highlight any cells where the score is zero. The scoring panel meetings start the week of Jan 18th but staff need some time with this information to prep.

**Comment by WendyKoelfgen** [comment]
For each application, display:
- application ID
- criterion ID and description as it appears in the scoring section
- each reviewer scores
- average score for each criterion

Staff will need to do the following. If there is a way to assist with this in the portal, that would be great:
- identify any criterion which has a 2+ score range (i.e. 0-2, 1-3, 2-4 or greater
- call out/highlight any zero scores

**Comment by CadyLister** [comment]
I see that this was closed but dont see the report in the portal, how do we see it? I did refresh

**Comment by derekwmiller** [comment]
you'll see it once I publish it. currently on dev. publishing is not the same as making a commit to the repo that logs the code and closes the issue
