### ISSUE TITLE
Last two reports needed

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#127]
Derek,
we have talked about both of these reports for a while but putting here with deadlines. These are the last two that we will need for this process. 
 
1. https://portlandoregongov.sharepoint.com/:w:/s/pcef/EYqkLmTDtYpHsGTdmmo7m-UB2yiyGHoYt8s59u_dfFVxfA?e=1HMUVm this is likely a report with a tab for planning grants, one for small and one for large - this is needed by January 29th
2. ability to download all data into csv with info formatted to deliver one row per application - needed as soon as it is available but no later than Feb 8th

**Comment by derekwmiller** [comment]
@CadyLister @WendyKoelfgen needs discussion

**Comment by derekwmiller** [comment]
@CadyLister I see you made edits to item 1 above. what is the 'criteria 3' score?

**Comment by CadyLister** [comment]
Hey, sorry i meant to send you an email as soon as i made that edit and then got sucked into a phone call and then forgot. Criteria 3 is scoring criteria 3 (same for planning, small and large) "Staff (including leadership) and board of the organization reflect the community the proposed project is intended to benefit."

**Comment by derekwmiller** [comment]
@CadyLister no worries. Sounds easy enough. Thanks
