### ISSUE TITLE
1254 should be physical improvements w/no construction workforce

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#135]
Application has "yes" on 1.13 and 3.5 but is still showing up in the portal as "no phys improvement - no construction workforce". 
![image](https://user-images.githubusercontent.com/68038292/104350979-a6db3980-54b9-11eb-86b0-108bc250f093.png)

**Comment by CadyLister** [comment]
to  add (hopefully) more clarifying info. 1254 was marked correctly (see screenshot below) I think the issue is the report

![image](https://user-images.githubusercontent.com/71226975/104363936-be6eee00-54ca-11eb-971d-e3185dbcdef6.png)

**Comment by derekwmiller** [comment]
@WendyKoelfgen @CadyLister where is it showing up incorrectly? don't see in either screenshot where it's marked incorrectly

**Comment by WendyKoelfgen** [comment]
The orange highlights in my screenshot are highlighting the criteria not required for "no physical improvements, no construction workforce". Criteria 11-14 should not be highlighted.
