### ISSUE TITLE
1328 not showing up in Scoring Panel Review report

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#136]
All of the other ones appear when clicked on 
![image](https://user-images.githubusercontent.com/71226975/104376520-f9c4e900-54d9-11eb-9d50-b16e42ec2cd1.png)

**Comment by derekwmiller** [comment]
fixed. caused by some apps having > 1 staff tech score, others (majority) only having 1

**Comment by CadyLister** [comment]
Thanks
