### ISSUE TITLE
Scoring Panel Review report problems

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#142]
Derek,
Wendy and I noticed some issues with the scoring panel review report. These are issues that, at least for the entirely missing scores, we are certain were not there at the beginning of the week. 

Panel 2
1340 – Missing Jaimes’ scores
 
Panel 3
1259 - Missing David Q19.
1276 - Missing David Q19.
1309 - Missing David Q19.
1359 – failed tech review, should not be included in the report
1368- failed tech review, should not be included in the report
 
Panel 4
1322 – Missing Ranfis’ scores
 
Panel 5
1438 – Missing Robin’s scores
 
Panel 6
1393 – Missing Wendy’s scores
1408 – Missing Wendy’s score
 
Panel 7
1430 – Missing Daniel’s scores
 
Panel 9
1253 -  Scores displayed on orange highlighted Q11, Q13, Q14. These scores should be removed, criterion should not have been available. 
1394 – Missing Jaimes/Ingrid Q19

**Comment by CadyLister** [comment]
These things are still outstanding

Panel 3
1359 – failed tech review, should not be included in the report
1368- failed tech review, should not be included in the report

Panel 9
1253 - Scores displayed on orange highlighted Q11, Q13, Q14. These scores should be removed, criterion should not have been available.

**Comment by derekwmiller** [comment]
done. also check email.
