### ISSUE TITLE
Staff score showing up in greyed out area

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#147]
Staff scores are appearing in the greyed out spots for the applications 1270. 1253, 1426 and 1439. If this doesnt impact anything then it may not matter but I am pretty certain I removed all the old staff scores so it is weird that they are showing up again.

**Comment by derekwmiller** [comment]
@CadyLister on what report?

**Comment by CadyLister** [comment]
when i look at my scores, though now when i look at 1270 i dont see it, but with 1253 still do

![image](https://user-images.githubusercontent.com/71226975/106966926-17f9bf80-66fb-11eb-9015-043f581222b3.png)

**Comment by CadyLister** [comment]
Just checked the others, looks like 1253 is the only one now showing up like this, weird. Maybe i was looking when  you were pushing new code and things got wonky.

**Comment by derekwmiller** [comment]
I have not pushed new code today

**Comment by derekwmiller** [comment]
question num 7 shouldn't be grayed out

**Comment by CadyLister** [comment]
you are right, i didnt even notice that was not a staff score

**Comment by derekwmiller** [comment]
i don't see it grayed out. everything that I see looks correct

**Comment by CadyLister** [comment]
it looks correct now to me as well but in the screenshot you can see that it was greyed out. maybe it doesnt matter but it made me uncertain about where things were coming from since i dont have another place where i recorded my scores

**Comment by derekwmiller** [comment]
Yeah I see your screen shot but I don't see an application ID#. sounds like you were looking at a handful of different applications?

**Comment by CadyLister** [comment]
1253, should have been more clear

**Comment by derekwmiller** [comment]
meant on the screenshot
