### ISSUE TITLE
greyed out score

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#149]
Found another one and got a screenshot with the app # in it this time, then when I refresh it is fixed. I dont know if this impacts anything but flagging bc its weird

![image](https://user-images.githubusercontent.com/71226975/106989855-eb0fd180-6727-11eb-90ea-1eebeca0ad78.png)

**Comment by derekwmiller** [comment]
Thank you for capturing the ID#. This is helpful and I will look in to it.

**Comment by derekwmiller** [comment]
@CadyLister question 9 isn't a staff score criteria. Not grayed out on mine and shouldn't be on yours. We'll need a screen share to resolve
![image](https://user-images.githubusercontent.com/2798800/107074062-0bc63e80-679d-11eb-90c8-0d1b94b4f9cb.png)
