### ISSUE TITLE
Progress report 

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#151]
These applications say they only have two submitted scores in the progress report but the new report where you show who has submitted a score shows three for all of them
1249
1260
1268
1274

**Comment by derekwmiller** [comment]
@CadyLister this is resolved, correct?

**Comment by WendyKoelfgen** [comment]
That is correct. The report now shows three sets of scores for every application.

**Comment by derekwmiller** [comment]
thanks @WendyKoelfgen
