### ISSUE TITLE
committee members need to see all applications - due Feb 10

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#152]
Derek,
following up on our meeting, Committee members need to be able to read all the applications. Scoring will be over so im not worried about them accidentally scoring something. I think either adding them to all panels or just making their accounts the same as staff would do the job. Their emails are pasted below, let me know if you need anything else

Squiemphen-Yazzie, Amanda <Amanda.Squiemphen-Yazzie@portlandoregon.gov>; 
Wang, Robin <Robin.Wang@portlandoregon.gov>; 
Villatoro, Ranfis <Ranfis.Villatoro@portlandoregon.gov>; 
Horst, Megan <Megan.Horst@portlandoregon.gov>; 
Sipin, Maria <Maria.Sipin@portlandoregon.gov>; 
Edden Hill, Michael <Michael.EddenHill@portlandoregon.gov>; 
Graham, Faith <Faith.Graham@portlandoregon.gov>; 
Moreland Jr., Jeffrey <Jeffrey.MorelandJr@portlandoregon.gov>; 
Clarke, Shanice <Shanice.Clarke@portlandoregon.gov>

**Comment by derekwmiller** [comment]
@CadyLister is there anyone that currently has access to the system that should not have access to all apps? They were on a scoring panel, but are not on the committee?

**Comment by WendyKoelfgen** [comment]
Yes. Danny, Ingrid, Leesha and Chanelle (city employees) and Amanda Zuniga are not committee members and are not PCEF staff but were on scoring panels.

**Comment by derekwmiller** [comment]
thanks @WendyKoelfgen
