### ISSUE TITLE
Financial review section

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#159]
This will be after eligibility and technical review (but should be able to do technical and financial concurrently). Financial review will have a Green, Yellow, Red ranking and will need a notes section for folks doing the financial review (will likely be staff). All reviewers need to be able to see this info (internal and external scoring panel members).

**Comment by derekwmiller** [comment]
@CadyLister any more detail here? Single question? Multiple questions?

**Comment by CadyLister** [comment]
@derekwmiller they should be able to give the application a score of red, yellow or green on the three things below

Intangibles – length of service and experience of staff
Financials - financial health of organization
Financial management practices
