### ISSUE TITLE
section 3 missing question numbers

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#16]
the first question in section 3 doesn't have a number. throws off the index btw the db and questions on all the other questions. 

fixed on my side but my questions now do not share the same numbers as yours

**Comment by derekwmiller** [comment]
small grant application fyi

**Comment by CadyLister** [comment]
This will be the same for the large grant application. I will adjust our documents so that what was 3.1 is now 3.2 and carry through for all questions in that section. We will need to double check once the online app preview is available so just let me know when I can get into that.

**Comment by derekwmiller** [comment]
resolved
