### ISSUE TITLE
need descriptions and dollar amounts for the 3 new grant types

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#167]
this will replace the latin that is currently in the portal

**Comment by derekwmiller** [comment]
https://portlandoregongov.sharepoint.com/:w:/r/sites/pcef/_layouts/15/guestaccess.aspx?e=X1DbWx&share=ER8TES_0vtBFkjcH5qpTAp4BgsUuwWRWMO5efKD0MHRH5A

**Comment by derekwmiller** [comment]
done

**Comment by CadyLister** [comment]
Updated welcome text and put in this doc, changes are relatively minor but important.

**Comment by CadyLister** [comment]
Also looks like the dates got updated in the mid page light blue banner but not the bottom on
