### ISSUE TITLE
Application title disappears from top of Section 1 after save and continue

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#168]
Standard grant - looks like it is retained in the application list on the home page

![image](https://user-images.githubusercontent.com/68038292/134233494-abc722dd-fb20-49e8-9e7e-fe7fe960258f.png)
![image](https://user-images.githubusercontent.com/68038292/134233534-48389b2c-1204-4e77-aa55-8f5323373cd1.png)

**Comment by derekwmiller** [comment]
fixed
