### ISSUE TITLE
Need to rename section 1 to section 0

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#174]
In all applications, need to rename/renumber section 1 to section 0

**Comment by derekwmiller** [comment]
Section 0? Why?

**Comment by CadyLister** [comment]
b/c we named it section 0 to differentiate from sections 1 on which can be responded to in a different format

**Comment by derekwmiller** [comment]
@CadyLister @WendyKoelfgen Changing section 1 to section 0 means renumbering the entire application. How is this the solution? What changed that prompted this?

**Comment by CadyLister** [comment]
The change was to differentiate what was going in the portal from the sections they put into the main application body. It was a communication with applicants decision. If this is not possible we need to know asap as I will need to make adjustments in a lot of other places.
