### ISSUE TITLE
small grant section 6

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#19]
the opening statement for this section asks for a certification # but there's no question for it... it's in parens in a block of text.

thoughts?

first bullet of the second paragraph

**Comment by CadyLister** [comment]
This is just the definition of diverse which is referenced in question 6.2, to be diverse as defined by the program you have to be either the first bullet in the list or the second

**Comment by derekwmiller** [comment]
right... so where do they provide their certification #?

**Comment by CadyLister** [comment]
We are not requiring verification in the application

**Comment by derekwmiller** [comment]
the document text for the beginning of section 6 is below. note the bold text.

For the purposes of this application, PCEF defines diverse contractors and subcontractors as follows: 
•	Certified by the State of Oregon’s Certification Office for Business and Inclusion (COBID) as a Minority-Owned Business Enterprise, Women-Owned Business Enterprise, Disadvantaged Business Enterprise, Emerging Small Business, or Service-Disabled Veteran Business (M/W/DBE/ESB/SDV) (**provide certification #**); or
•	A nonprofit or non-COBID-certified business that can demonstrate majority ownership and leadership by women, people of color, people with disabilities, the chronically underemployed, or other historically disadvantaged populations. Defined as follows: 
o	Be registered with the Oregon Secretary of State. 
o	Have gross annual receipts (3-year average) that do not exceed $23.98 million. 
o	Demonstrate control and management of day-to-day operations that are led by persons from the defined population.
o	For nonprofit organizations, demographics of the board of directors and executive staff are 51% or greater of the defined populations.
o	For businesses, ownership of 51% or greater is held by persons from the defined populations, and owner is not an owner or partial owner of other construction/construction-related firms.

**Comment by WendyKoelfgen** [comment]
Please delete "(provide certification #)"
