### ISSUE TITLE
standard app

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#190]
app requires applicant EIN even if applying with a fiscal sponsor is chosen and an EIN is entered for the fiscal sponsor. This appears to be the case for all application types

**Comment by derekwmiller** [comment]
Is that not the intent?

**Comment by CadyLister** [comment]
Some folks who apply with a fiscal sponsor will have a status with the IRS and in those cases they will have an EIN and we would want it. However, in some cases folks are applying through a fiscal sponsor it is because they are just a group of people with no legal status and in those cases they wont have an EIN of their own. In ALL cases if they applying through a fiscal sponsor we need the fiscal sponsor EIN.

**Comment by derekwmiller** [comment]
OK. Based off that logic, how do I know if an applicant has an EIN or not?

**Comment by CadyLister** [comment]
If they are NOT applying with a fiscal sponsor they need an EIN
If they ARE applying with a fiscal sponsor the EIN is optional (sometimes they will have one and sometimes they will not)

**Comment by WendyKoelfgen** [comment]
If this is hard to do, we could include instruction for folks to enter "NA" in that field when they are applying with a fiscal sponsor and do not have their own EIN

**Comment by derekwmiller** [comment]
It's not difficult, there's simply no logic to fully vet the fiscal sponsor route. If you are applying with a fiscal sponsor, there's nothing in the data that informs the application (me) whether you have an EIN and have failed to provide it or that you do not have an EIN and that's why the field is blank.

**Comment by WendyKoelfgen** [comment]
Right. Would it make sense to make the field required for all and include the instruction "Please enter NA if you are applying with a fiscal sponsor and the sponsored organization does not have an EIN"?

**Comment by derekwmiller** [comment]
I think it would make more sense to add a question "Do you have an EIN?". Otherwise, we get into NA vs N/A vs None vs No, etc.

**Comment by CadyLister** [comment]
Derek, if adding the question you posed is easy please do that. If not we will just have to live with it being potentially missed sometimes.
