### ISSUE TITLE
staff scoring not saving

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#204]
staff scoring doesnt have its own submit button and when you enter values and then scroll to very bottom and hit save the entries disapear https://www.portlandmaps.com/bps/pcef-grants/internal/#/standard/2633/3

**Comment by derekwmiller** [comment]
![image](https://user-images.githubusercontent.com/2798800/143085298-4129bfca-6af1-4ca2-abff-40e2afe5edb7.png)
