### ISSUE TITLE
standard grant - large - physical improvement all others

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#205]
https://www.portlandmaps.com/bps/pcef-grants/internal/#/standard/2634/3
Large standard grant with physical improvements but NOT a single site $350K or greater issues
1. dont get the got it confirmation when saving technical review
2. staff scoring no save button and entries disapears when hit save button above ( for financial review), save button at bottom not available
3. panel scoring wont show up (see screenshot below)
![image](https://user-images.githubusercontent.com/71226975/143031344-51062f22-87b8-4083-b278-021128028810.png)

**Comment by derekwmiller** [comment]
@CadyLister 
![image](https://user-images.githubusercontent.com/2798800/143085409-8ea42780-6bb3-405b-84ff-ab0d90179aa5.png)
