### ISSUE TITLE
Technical review dropdowns not available - app 2658

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#214]
@derekwmiller I created a new application to test the technical review because it the dropdown options only appeared to be working in apps where i had already entered values. I created app 2658 this morning and ran into same problem as in the other issue i posted, not dropdown option so cannot proceed with testing

https://dev.portlandmaps.com/bps/pcef-grants/internal/#/standard/2658/3

**Comment by derekwmiller** [comment]
@CadyLister all applications must pass eligibility review before any other review can be completed

**Comment by CadyLister** [comment]
@derekwmiller I had checked yes, entered text in the notes box and hit save. Just went back in to double check and did that again, still cannot access the technical review in either of the applications i created Friday
