### ISSUE TITLE
Standard Large Yes $350K - staff scoring save button not working - app # 2658 

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#217]
The staff scoring button is not working, i saved eligibility, tech review and financial review, entered values for staff scoring but the button was not available to push (little red circle showed up when i hovered over it). I tried entering all panel scores and hitting save at the bottom of the page which worked for panel scores but the staff scores disappeared.

Other than this issue everything appears to be working and correct on Large Standard apps with single site $350K+

**Comment by derekwmiller** [comment]
@CadyLister I cannot replicate this and am going to close the issue. If the issue persists, please reopen or create a new issue.
