### ISSUE TITLE
Home - scoring section appended to bottom of app list

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#220]
When using the home button to return to the list of apps from a scoring section, the scoring section appears to be appended to the bottom of the app list

![image](https://user-images.githubusercontent.com/68038292/143900698-8e80d495-c621-4b99-8af4-f173b2ea9eeb.png)

**Comment by WendyKoelfgen** [comment]
Only seeing this in production. Not seeing it happen in dev

**Comment by derekwmiller** [comment]
@WendyKoelfgen this was resolved in dev last week
