### ISSUE TITLE
Report needed Wednesday morning

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#226]
Need an excel from the portal that has: 1) ID, 2) grant type, 3) project type, 4) applicant org name, and 5) amount requested for all submitted applications.

**Comment by CadyLister** [comment]
would like to add if possible 6) name of primary contact and 7) email of primary contact

**Comment by derekwmiller** [comment]
@CadyLister @WendyKoelfgen project type? the only project type I'm aware of that is available on application submission only applies to planning grants. question 16 I think. Otherwise, it's not available until technical review (and then, only for standard)

**Comment by CadyLister** [comment]
@derekwmiller  you are right, we removed the question about project type and replaced it with four questions about % of budget to each funding area. Just drop this requirement, it will be easy for us to figure out.

**Comment by derekwmiller** [comment]
report is ready. will run first thing in the AM

**Comment by CadyLister** [comment]
Thanks Derek!

**Comment by derekwmiller** [comment]
@CadyLister report sent
