### ISSUE TITLE
Standard large phys impro single site +350k 2633

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#234]
1) Can't save staff scores
2) Can't modify technical review (I was able to unlock technical review by hitting "Not required". It cleared my selections and then I was able to go back and make new entries and save)

**Comment by WendyKoelfgen** [comment]
On further testing, its the yes/no radio buttons on technical review that cannot be modified. The drop downs seem to work.

**Comment by WendyKoelfgen** [comment]
Also, after all of this modifying, now I can save staff scores

**Comment by derekwmiller** [comment]
@WendyKoelfgen can you help reproduce this issue when you have a moment? MS Teams preferred
