### ISSUE TITLE
Sent to scoring panel button

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#238]
We need a button that indicates if something is being sent to scoring panel where it will have three reviewers (staff who already scored it, committee member and a third who is either another staff or a community cohort member). 

The threshold review process means that applicants who score less than half possible points will not be advanced to a scoring panel. Of the number of applications that get half or more of all possible points 90 of them will be sent to scoring panels, there will likely be around 50 to 70 that do not go to scoring panel, for those applications the scoring that staff did will be the only score for those applications. 

All applications that pass eligibility and technical review need to show up int eh report for Council

**Comment by derekwmiller** [comment]
@CadyLister and I discussed. This will not be necessary. Instead, we will determine whether an application has been sent to a scoring panel based off it being assigned to a panel.
