### ISSUE TITLE
Threshold Progress Report

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#241]
Need this one by January 21
Note that some applications will get scored by 3 people (full panel review), and some by 1 person (entering one score for two staff).

**Comment by derekwmiller** [comment]
the 90 to the panel will be scored by 3; applications not sent to the panel will be scored by 1 (threshold score is final score)

**Comment by derekwmiller** [comment]
needs to run off of panel scores and threshold scores

**Comment by derekwmiller** [comment]
need to flag whether threshold review is missing required criteria
