### ISSUE TITLE
Committee Council Report

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#244]
This one needs to be done by mid-March but would love to have it earlier
Things to note/change
1 - will need to include scores for applications that have one reviewer and those that have three and display them in the same way
2 - section scores no longer relevant this round, replace with each criteria same as preliminary score report
3 - eliminate column for project type since that is no longer captured in portal

**Comment by derekwmiller** [comment]
@CadyLister let's discuss this one

**Comment by CadyLister** [comment]
k, i will set up a meeting.

**Comment by CadyLister** [comment]
4/14 meeting follow up
1. Cady needs to confirm with Sam that we are going one score
2. Derek will think on the button for Committee recommends/not recommends and funded/not funded button
3. Derek will add a button to categorize grants into 1) planning, 2) WCD 3) Clean Energy (standard), 4) Regenerative Ag/Green Infrastructure (standard), 5) Innovation (standard). done by first week of May

**Comment by derekwmiller** [comment]
@CadyLister 
need confirmation on one score

**Comment by derekwmiller** [comment]
- add ranking to report (1 of xx)
