### ISSUE TITLE
threshold scoring report returning incorrect scores

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#257]
Example - application 2717 says it got a 98 in the threshold report but it is missing a GHG value and should be returning a value of 84.4

**Comment by CadyLister** [comment]
I went through and spot checked several other apps and they all returned correct scores so not sure what is going on here

**Comment by derekwmiller** [comment]
@CadyLister  I'm seeing 92.4 and all required values present?

**Comment by CadyLister** [comment]
Yeah, that is what i see now too.  Everything seems to be working now
