### ISSUE TITLE
Scoring panel assignments

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#262]
Link below to scoring panel assignments

https://portlandoregongov.sharepoint.com/:x:/s/pcef/Ea4Fn7H0XDdKvUYNqS5euyUBqzM6ZTKjQsUA1hXl1R3XEg?e=8cnzkS

**Comment by derekwmiller** [comment]
@CadyLister check out the tab "Derek - Panel Assignments" in the same file. Thoughts?
this would prevent any added hoops on queries / reports and would clean up the review report
