### ISSUE TITLE
Facilitators portal access - IF EASY

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#263]
Derek, 
these two folks are the facilitators for our scoring panel meetings. It would be great if they could get access to the portal reports, they will need to show the panel review report for those meetings.  Caveat is that if this is not fast and easy we can just have staff be the screen sharers since they already have access and will be in every panel meeting. 

Irene Kim irene@cascadia-partners.com
Ayano Healy ayano@cascadia-partners.com

**Comment by derekwmiller** [comment]
@CadyLister 
To grant them access, they would have to be added as either a pcef user or a score panel user. The former would grant them the same level of access as you, Wendy, etc. The latter would would add them to panel-level reporting (i.e. they would have to be assigned to panels to see applications & scores for that panel).
Advise on how you'd like to proceed.

**Comment by derekwmiller** [comment]
@CadyLister 
scratch the above. Only PCEF users have access to view the panel score report. I do not recommend giving these users the same level of access.
