### ISSUE TITLE
grant application 'sub-category'

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#265]
Derek will add a button to categorize grants into 1) planning, 2) WCD 3) Clean Energy (standard), 4) Regenerative Ag/Green Infrastructure (standard), 5) Innovation (standard). done by first week of May

**Comment by derekwmiller** [comment]
@CadyLister for standard grants, are there any that fall into more than one category?

**Comment by CadyLister** [comment]
There are some that have activities in multiple categories but we are assigning to the category that represents the majority of their funding so I dont think we need the option for multiple categories and for purpose of ranking we need them in just one
