### ISSUE TITLE
Committee report

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#266]
2629 is marked eligible in portal but shows up as NOT eligible in report
2749 is marked NOT eligible in portal but shows up as eligible in report

Both of these were originally the opposite and were changed a while back (eg originally 2749 was marked eligible but then they withdrew so I changed them to not eligible with a ntoe)

**Comment by derekwmiller** [comment]
fixed.
future changes to eligibility will be reflected in report
