### ISSUE TITLE
ranking ineligible applications

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#267]
Derek,
there are 8 applications that are WCD or Planning that were automatically given a funding category and so they are counted into the ranking and total # which we do not want. Can you make it so they do not have a funding category? 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/clister/AppData/Local/Temp/2/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/clister/AppData/Local/Temp/2/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

APP_ID | ELIGIBLE | GRANT TYPE | FUNDING CATEGORY | APPLICATION TITLE | FUNDING CATEGORY RANK | APPLICATIONS IN FUNDING CATEGORY
-- | -- | -- | -- | -- | -- | --
2707 | No | planning | planning | Sustainable Indigenous Marketplace | 11 | 42
2531 | No | planning | planning | SAMCO | 37 | 42
2594 | No | planning | planning | Climate Change | 37 | 42
2756 | No | planning | planning | EGC Planning Grant 1 | 37 | 42
2667 | No | planning | planning | GRAVITY ENERGY MACHINE PROJECT (GEM) | 37 | 42
2669 | No | planning | planning | Climate adaptation, vulnerability and community well-being project. | 37 | 42
2691 | No | planning | planning | I'm Hooked Inc. Educational and Conservation Center | 37 | 42
2718 | No | wcd | wcd | Hollywood East | 41 | 41

</body>

</html>

**Comment by derekwmiller** [comment]
@CadyLister is this because they are ineligible?

**Comment by CadyLister** [comment]
@derekwmiller  yeah, the ones on this list are all inelgible (or they withdrew so I marked them ineligible so they wouldnt get pulled into the reports)

**Comment by derekwmiller** [comment]
@CadyLister should they be excluded from the report entirely, or excluded only from the rank?

**Comment by CadyLister** [comment]
@derekwmiller just from the rank/ranking

**Comment by derekwmiller** [comment]
@CadyLister run it now please

**Comment by CadyLister** [comment]
@derekwmiller just ran it and it only returned column A with the app ID's and no other info

**Comment by derekwmiller** [comment]
@CadyLister yeah that's interesting. I'll look in to it

**Comment by derekwmiller** [comment]
@CadyLister I rolled back my attempted fix. The report now includes all data but still ranks the ineligible records.
The report relies on a value being present in the 'funding_category' column. I can either modify / rewrite the report or - more quickly - assign ineligible records to their own funding category so that they are ranked amongst themselves (essentially meaningless)

**Comment by CadyLister** [comment]
@derekwmiller please go with the easier quicker option,. thank you!

**Comment by derekwmiller** [comment]
@CadyLister this is resolved
thanks
