### ISSUE TITLE
scores now showing in Score History Report

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#268]
@derekwmiller  the I pulled the score history report b/c i needed the find all the criterion 10 scores for planning grants that had NOT been sent to a scoring panel. I noticed that they were not showing up and assumed it was b/c the scores had been entered a long time ago and I needed to hit the save button which I did for all planning applications staff scoring that did not go to scoring panels...but it didn't fix the problem, some examples are the applications below

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/clister/AppData/Local/Temp/4/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/clister/AppData/Local/Temp/4/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

2557
--
2677
2771
2632
2720
2653

</body>

</html>

**Comment by derekwmiller** [comment]
@CadyLister 

Criteria 10 on planning grants is a staff score. It is in the staff score history report.

I do not see any scores entered by you in the planning grant scores table today. Which save button were you hitting?

**Comment by derekwmiller** [comment]
@CadyLister 
Looks like you were using the staff score save button. That's fine and will not impact any reports.
You just need to run the staff score history report.
