### ISSUE TITLE
@derekwmiller  There are 9 records that need some sort of note indicating that we requested they modify their proposal so the application material will differ from the final recommended project. It could just be a note on those records or maybe in the project description. Do you have any other thoughts on this?

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#273]
@derekwmiller  There are 9 records that need some sort of note indicating that we requested they modify their proposal so the application material will differ from the final recommended project. It could just be a note on those records or maybe in the project description. Do you have any other thoughts on this?

_Originally posted by @CadyLister in https://github.com/BPSTechServices/pcef-public/issues/271#issuecomment-1187398009_

**Comment by derekwmiller** [comment]
@CadyLister what do you need this note to do? Do you need to be able to select records based off the presence of this note in the future? Etc.

**Comment by CadyLister** [comment]
@derekwmiller  The note is just to notify people that the program requested that the applicant accept specific modifications (we have these in a bulleted list) prior to funding. This means that the original application material will differ from what is recommended for funding. It is likely, but not 100%, that we will need this in the future as well.

**Comment by derekwmiller** [comment]
@CadyLister you're going to need a new value flag in the database to indicate whether this situation applies to a given record (true / false). Notes are contextual -- they would be appropriate to hold the textual information of what modifications were requested, but not for querying or retrieving records from the database at a later date.

I'll need a list of ID numbers where this applies.

**Comment by derekwmiller** [comment]
done
