### ISSUE TITLE
funding process language for 'main' page

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#276]
@CadyLister 
need content / language to include for the recommendation / approval / funding disbursed process

**Comment by CadyLister** [comment]
Final language below:
PCEF grant applications must first be recommended by PCEF Committee and then approved by City Council. The Committee recommended a portfolio of grant applications to City Council on June 2, 2022. City Council approved the recommendation on July 20, 2022 and directed program staff to conduct an additional 45 days of due diligence prior to final funding awards.

**Comment by derekwmiller** [comment]
@CadyLister 
This does little to explain how that process applies to how the data is presented on the page, and I am reluctant to modify it since it had to be 'approved'. 
I thought the intention of this language to help explain to people why there were multiple columns and filters?

**Comment by derekwmiller** [comment]
@CadyLister disregard the previous. This works just fine for now and can be modified if necessary. All good.
