### ISSUE TITLE
Help text - Priority Populations

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#3]
Hey @derekwmiller  - We have one term, “priority population” which we think needs to be defined for everyone who reads the application (whether they scroll over the term or not). That term shows up 13 times in the large application and is dispersed throughout. This is different than the terms that we are defining for hover/pop-up definitions. Everyone needs to see it. How would you recommend handling that?

**Comment by derekwmiller** [comment]
there needs to be a 'help' page that includes all definitions. please provide the content.

**Comment by derekwmiller** [comment]
resolved
