### ISSUE TITLE
discrepancies between applications

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#35]
as a general rule, where there are minor discrepancies (same meaning... slightly different language, difference in suggested word count, etc) between the applications (same question ... different grant type) --- I've tried to be consistent.

question 2.2 small / large grant is an example. in this case, I did NOT make the questions consistent.

suggested word count on 2.3 is a case where I did make them consistent

**Comment by CadyLister** [comment]
There are intentional differences in suggested word count. There shouldnt be differences in language for stuff that means the same thing.
