### ISSUE TITLE
large application 6.8

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#36]
i need a list of 'diverse contractor' designations

**Comment by CadyLister** [comment]
It is in the text at the start of section 6, maybe edit text in 6.8 to below:

"Identify whether the contractor meets PCEF requirements for being a diverse contractor (see definition of diverse contractor at the beginning of Section 6) and, if so, which designation."

**Comment by derekwmiller** [comment]
I used this to save words: Identify whether the contractor meets PCEF requirements for being a diverse contractor (as defined at the beginning of this section) and, if so, which designation.

Let me know if that doesn't work
