### ISSUE TITLE
Planning grant text changes - from online review

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#37]
Question 1.1 – spell out “semi-colon” and put “;” in  parenthesis. Alternately we could delete this instruction, it doesn’t seem necessary
Question 1.2 – 1) change instructions about how to select multiple things to “use Cntrl key on your keyboard to select multiple” 2) change “other” next to text box to “Other/innovation”
Questions 1.15 and 1.17 – change from “No, this organization is not…” to “No, this project is not…”
Question 2.5 – delete word “either” in paragraph 2

**Comment by derekwmiller** [comment]
separating text input by a character (semi-colon, comma, pipe, backslash, etc) is absolutely necessary for data analysis and reporting. otherwise, it's a simple long piece of text that you cannot ask questions of
