### ISSUE TITLE
Closing survey

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#4]
Hey @derekwmiller - We want to add 2-3 questions for anonymous feedback. We want people to participate but also to trust that it is anonymous. Can this be supported in the same system or should we create the survey somewhere else and link to it? Ideas?

**Comment by derekwmiller** [comment]
It can be supported in the same system but I wouldn't recommend it. 1 - it's late in the game to be adding features. 2 - something like this can be easily accommodated by survey monkey.

**Comment by WendyKoelfgen** [comment]
Ok. The team wants the survey questions to happen at the end of the application. This is more important than anonymizing the responses. I will email you a link to the document with the final questions
