### ISSUE TITLE
Planning grant #2.2

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#42]
Question 2.2 needs instructions for optional upload

**Comment by derekwmiller** [comment]
there is no <<file input>> denoted in the document

**Comment by derekwmiller** [comment]
Sorry the markdown messed up that comment. 

There is no file upload input notes in the document

**Comment by CadyLister** [comment]
I just refreshed and it looks like this is taken care of, it was an oversite on our part that there was not upload field indicated. Thanks for taking care of it!
