### ISSUE TITLE
Planning grant #2.5 - need hover text 

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#43]
Question 2.5 – needs a hover text for the Asterix, the info is at bottom of question but not visible when you are on the beginning of the question

**Comment by derekwmiller** [comment]
an asterix is too small of a target for hover text. users won't be able to access it. further... the hover text you're referring to is pretty large for a tooltip.

**Comment by CadyLister** [comment]
ok, hopefully they will have already read the whole question by the time they get to the online app and if not they will contact us
