### ISSUE TITLE
Small grants - reference to budget question/section

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#46]
6.1 and 6.3 say to skip to 6.5 but it should be budget section, it does seem a little strange to have a whole new section for one question that then asks you to go to the upload section. We could have it say …skip to budget question below… or ….skip to budget question at the end of this section. Open to ideas but having it be 6.5 doesn’t work well since it is not related to workforce.

**Comment by derekwmiller** [comment]
I think we solved this by adding 'budget' to the section headings, correct? feel free to open it back up if not
