### ISSUE TITLE
Small grant - attachment A not a thing to upload

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#47]
3.4 – attachment A is not something you upload, it is just a list of information requirements to include in your project description and scope, no upload instruction needed. Open to ideas about how to make this more clear

**Comment by derekwmiller** [comment]
@CadyLister  can you confirm whether or not there's anything to do with this issue? Seems like we changed the language on the question and resolved it.
thanks.

**Comment by CadyLister** [comment]
Looks like this one is resolved
