### ISSUE TITLE
Large grant - 6.15 and 6.16 structure

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#50]
6.15 and 6.16 structure is off and missing final question at end. Pasted below is how they should appear and are referenced in guidance documents. May be easier to talk through let me know
6.15  	Provide your commitments to employ apprentices on the proposed project. (If the project does not include apprenticeable trades, skip to section 6.16.b., below.) We understand that people may fall into more than one category; disaggregated information will be collected during project reporting, 
a.	____% of total work hours that will go to apprentices (amount of work that will be completed by apprentices)
b.	____% of total apprentice hours that will go to all priority populations (how much of the apprentice work will be completed by people who are in PCEF priority populations).
i.	____% of apprentice hours that will go to people of color 
1.	____% of total apprentice hours that will go to women who are people of color 
ii.	____% of apprentice hours that will go to White women
iii.	____% of apprentice hours that will go to other priority population(s). Please define:______________________________
6.16  	Provide your commitments for journey-level/non-apprentice workers on the proposed project. We understand that people may fall into more than one category; disaggregated information will be collected during project reporting.
a.	____% of total work hours that will go to journey/non-apprentice workers (i.e., how much of the work will be completed by workers that are not apprentices)
b.	____% of total journey/non-apprentice hours that will go to all priority populations (i.e., how much of the apprentice work will be completed by people representing PCEF priority populations).
i.	____% of journey/non-apprentice hours that will go to people of color   
1.	____% of journey/non-apprentice hours that will go to women who are people of color (subset of 6.16.a.iii above)
ii.	____% of journey/non-apprentice hours that will go to White women  
iii.	____% of journey/non-apprentice hours that will go to other priority population(s). Please define:______________________________
c.	Describe how the workforce utilization estimates were generated. (200-300 words)

**Comment by derekwmiller** [comment]
I don't understand how this is different than what is in the online form. It asks for the same information. The structure of a word document is not always the best way to structure an online form.

**Comment by derekwmiller** [comment]
missing workforce utilization question added
