### ISSUE TITLE
Large grant - reference to budget section issue

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#52]
6.1 , 6.4 say to skip to 6.5 but it should be budget section, it does seem a little strange to have a whole new section for one question that then asks you to go to the upload section. We could have it say …skip to budget question below… or ….skip to budget question at the end of this section. Open to ideas but having it be 6.5 doesn’t work well since it is not related to workforce.

**Comment by derekwmiller** [comment]
instructing users to look 'above' or 'below' is ambiguous at best. it needs a number so that users know exactly where it is. the fact that it was included at the end of the workforce section and not it's own is what it is, and it's too late to change at this point.

**Comment by CadyLister** [comment]
Let's rename Section 6 to have the words "and budget" at the end.

**Comment by derekwmiller** [comment]
great idea. i like it
