### ISSUE TITLE
final application step -- submit

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#6]
Unlike the paper applications, for the online forms you need one final action by the user -- submit this application

This is different than the 'save progress' action for each section

You'll need text to accommodate this action

**Comment by WendyKoelfgen** [comment]
This is the statement that they see before clicking submit or what the receive after clicking submit or both?

**Comment by WendyKoelfgen** [comment]
Also, do you need content for a confirmation email?

**Comment by derekwmiller** [comment]
The statement they see before clicking the 'Submit this application for consideration' button (button won't say all that).

yes. i need confirmation email text. i'll open an independent issue for that
