### ISSUE TITLE
Large grant upload section

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#62]
I saw a few issues on this section.

1. It would also be great (though not totally needed) if we could put the dropdown menu that has the question # above the upload file here button and give the # numbers descriptions of files to upload

2. Uploading files seems to take a long time which is ok but maybe we should put a statement in there telling people to give it time before assuming it isnt working. 

3. The large grant upload section says Planning grants and appears to have planning grant requirements. Pasted below is suggested changes to text/requirements. 

Large grant applications ask for the following documents:

Required:
2.9 – Financial documents: Current year board approved budget and three most recent full year financial statements (audited if available) 
3.4 - Attachment C: Milestones and activities
6.17 – Attachment B: Budget

Optional:
1.2 and 2.8 - Fiscal sponsor agreement (if applicable)
2.2 – Supporting documentation describing how your organization prioritizes and serves one or more of the PCEF priority population(s). (if applicable)
3.9 – Resumes (if applicable)
Other documents that support application

**Comment by derekwmiller** [comment]
think this is resolved. open it back up if it's not
