### ISSUE TITLE
Small Grant Testing issues

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#63]
Haven't finished but here is what I have so far:

Section 1 - can't seem to save and continue
Section 2 - clicked save, got the success message but then content disappeared? When I click back to section 2, there is no content
Section 3 - partially filled and tried to click back to section 2. Got the "you have unsaved changes" notice but the "save" button is opaque and can't be clicked, tried save and continue, same as section 1, turned opaque and did not give a success message
Section 6 - same save issue
3.2 - can we make it so the numbers can't be negative? Only instance where they may need to be negative would be the budget questions 2.10 a and b.
Section 7 - let me upload 1 document, then the Upload file button turned opaque and could not upload additional

**Comment by derekwmiller** [comment]
Well that doesn’t sound good...
