### ISSUE TITLE
Planning grant questions and uploads that are NOT required

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#64]
Planning grants - this is what is NOT required with some qualifiers
Questions:
1.6 - name of ED/Board chair (not required if applying with fiscal sponsor, which is question 1.3)
1.7 - this question has four fields, we really only need the name and one contact info (email or telephone)
1.11
Uploads that are NOT required
1.3 fiscal sponsor agreement
2.2 - alternate doc
2.7 - alternate doc

**Comment by derekwmiller** [comment]
1.11 -- not required at all or not required if not a registered non-profit?

**Comment by WendyKoelfgen** [comment]
These are, "if you have them, please include them but if you don't no worries". Does that make sense?

**Comment by WendyKoelfgen** [comment]
I realize I didn't answer your question. I am logging into the app now. Stand by.

**Comment by WendyKoelfgen** [comment]
1.11 is not a required question to answer

**Comment by derekwmiller** [comment]
1.9 is required if longer than 1 year, correct? not on the list above

**Comment by derekwmiller** [comment]
also file for 3.4 is optional if the input contains values, no?

**Comment by WendyKoelfgen** [comment]
1.9 - text is required in the provided field if value is more than 1 year
3.4 - I think its fine to make it optional no matter what. They may not have identified the project team yet. The upload is for resumes, if they want to include them. Looks like we lost that direction in the question.

**Comment by WendyKoelfgen** [comment]
I just talked to Cady about 3.4. Can we get rid of that upload altogether? They have a field to enter the requested paragraphs. They do not need to also upload the paragraphs in a separate document. That would be redundant. If they want to submit resumes, they can use the Optional upload.

**Comment by derekwmiller** [comment]
3.4 is listed as an optional, alternate file. This question only came up because it was not in the list of NOT REQUIRED files. It's fine as it is.
