### ISSUE TITLE
All grant types - required and not required info

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#65]
Just want to confirm that:
1. there will not be any visual indication on the application of what is required and what is not required. The only place people will see this is in the review section for questions and in the upload section for uploads
2. the requirements will know about the skip pattern, i.e. applicants will not be required to submit info for question they skipped.

**Comment by WendyKoelfgen** [comment]
Also, in the Accompanying documents section for all grants is the following statement "Fiscal sponsor agreement. This is required if you are submitting with a fiscal sponsor" 

This is not a required upload for any type of application. An org working with a fiscal sponsor may not have a formal written agreement to input in this space.

Please change to "Fiscal Sponsor agreement. Please upload if you are applying with a fiscal sponsor and if you have a documented agreement with the Fiscal Sponsor"

**Comment by derekwmiller** [comment]
@CadyLister 

Just want to confirm that:

1. there will not be any visual indication on the application of what is required and what is not required. The only place people will see this is in the review section for questions and in the upload section for uploads

- not exactly. if a question is affected by a skip, that question is disabled both visually and functionally

- if you want visual cues for 'optional' question, we can do that, but I don't have what I need to accomplish that readily available at my fingertips

2. the requirements will know about the skip pattern, i.e. applicants will not be required to submit info for question they skipped.
correct

**Comment by derekwmiller** [comment]
@WendyKoelfgen fiscal sponsor is no longer required. The text has been changed and requested to be changed in other issues
