### ISSUE TITLE
Small grant info NOT required

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#69]
Small grant questions that are NOT required
1.4
1.6 (if applying w fiscal sponsor)
1.7 (only really need contact name and one way to contact)
2.4
2.6 (if applying w a fiscal sponsor)
2.11.
3.2
3.3
4.2
5.2
5.3
5.4

Small grants attachments that are NOT required:
1.2 fiscal sponsor agreement
2.2 optional supporting docs
2.8 fiscal sponsor agreement
3.8 resumes

**Comment by derekwmiller** [comment]
@CadyLister @WendyKoelfgen 2.6 isn't required? that's a big section

**Comment by CadyLister** [comment]
2.6 is not required if they are applying with a fiscal sponsor. If they are applying directly (they are a non-profit) it is required
