### ISSUE TITLE
Planning grant review 9.18.20

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#71]
1.6 and 1.7 - default text says Jane Doe, change to Jane Smith
1.9 - don't need days/weeks as options for timeframe and set min value to 0
1.10, 1.12, 1.13, 1.15 - clicking ineligible response does not stop you from advancing
1.11 - don't need days/weeks as options for timeframe and set min value to 0
Section 4 needs to be updated but this is covered in another issue so not repeated here
Can only upload one document
Section 5 - review application button doesn't do anything
Section 5 - cannot click confirmation button and cannot click submit (maybe b/c you cannot do the review part)

**Comment by derekwmiller** [comment]
- [x] 1.6 and 1.7 - default text says Jane Doe, change to Jane Smith

- [x] 1.9 - don't need days/weeks as options for timeframe and set min value to 0

- [x] 1.10, 1.12, 1.13, 1.15 - clicking ineligible response does not stop you from advancing

- [x] 1.11 - don't need days/weeks as options for timeframe and set min value to 0

- [x] Can only upload one document

- [x] Section 5 - review application button doesn't do anything

- [x] Section 5 - cannot click confirmation button and cannot click submit (maybe b/c you cannot do the review part)
