### ISSUE TITLE
ineligible responses

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#74]
what is your ideal scenario when a user selects an ineligible response on one of these grant forms?

**Comment by WendyKoelfgen** [comment]
A pop up box with something like this - "This project is not eligible for a PCEF grant. If you have questions, please contact us. If you would like to modify your response, close this box and proceed." Not sure what the process would be to change their response so please modify the language as needed.

**Comment by WendyKoelfgen** [comment]
Also, they should not be able to proceed with the application unless they modify to an eligible response

**Comment by derekwmiller** [comment]
The workflow for this is confusing. Users can save and return. Users can also complete the sections in any order they choose. So - potentially - users could have the entire application submitted and ready for review before selecting an ineligible response.

Seems to me that we should alert users that an ineligible response will disqualify their application but not prevent them from continuing. Obviously, an ineligible response will prevent the application from passing the review, but I don't think it should impact the application before then.

If you disagree please let me know but that's how I see it.

**Comment by WendyKoelfgen** [comment]
Ah, I see. Ok. I was hoping we could stop them from proceeding at that question but I get it. Alright, how about this? Is this clear enough?

Stop. This project is not eligible for a PCEF grant. While you will be able to continue filling out the application, you will not be able to submit your final grant application with any ineligible responses. If you would like to modify your response, close this box and proceed. If you have questions, please contact us at cleanenergyfund@portlandoregon.gov

**Comment by derekwmiller** [comment]
I think that's too much.

I have a solution. It will be one of the last things I implement considering the form works fine as it is. If users submit an ineligible response they are prevented from submitting the final application.

**Comment by derekwmiller** [comment]
@WendyKoelfgen @CadyLister 

what do you want the red box to say?

![image](https://user-images.githubusercontent.com/2798800/93944794-81e47000-fcea-11ea-98b0-a0f4502c03fc.png)
