### ISSUE TITLE
Planning application review 9.21.20

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#75]
1.4 - Upload instruction text says “Attach the contract defining the fiscal sponsor agreement. Upload this file in Section 4: Accompanying documents.” Change to say “If you have a contract defining the fiscal sponsor agreement please upload this file in Section 4: Accompanying documents”

1.10, 1.12, 1.13, 1.15, 1.17 – selecting option that makes you ineligible does not stop you from proceeding (this is not that big a deal, we could leave it as is if needed)

2.5 – 1) should be able to enter 0 for a, b and c or give instructions to leave blank. 2) Thank you for including the info that was in the Asterix as hover text. 3) this question should be made optional for people applying with a fiscal sponsor (if they answered Yes to 1.3)

3.4 – delete alternate upload

Section 4 - Move #1.3 – Fiscal sponsor agreement to optional uploads list and delete last sentence (should read “#1.3 – Fiscal sponsor agreement.”

Section 5 - Review application said I had one or more not done in Section 2 b/c I had left some of 2.5 blank so that one needs to be able to accept 0 or no entry.

**Comment by derekwmiller** [comment]
1.10, 1.12, 1.13, 1.15, 1.17 – selecting option that makes you ineligible does not stop you from proceeding (this is not that big a deal, we could leave it as is if needed)

this is addressed in #74

**Comment by derekwmiller** [comment]
why delete the alternate file upload in 3.4?

**Comment by derekwmiller** [comment]
fiscal sponsor agreement is optional?

**Comment by derekwmiller** [comment]
there is no upload on 1.4
1.4 - Upload instruction text says “Attach the contract defining the fiscal sponsor agreement. Upload this file in Section 4: Accompanying documents.” Change to say “If you have a contract defining the fiscal sponsor agreement please upload this file in Section 4: Accompanying documents”

**Comment by derekwmiller** [comment]
@CadyLister I've done all I can do on this without responses to the questions above

**Comment by WendyKoelfgen** [comment]
looks like she means 1.3 instead of 1.4

**Comment by WendyKoelfgen** [comment]
yes. fiscal sponsor agreement is optional. they may not have a formal agreement in writing even if they have a fiscal sponsor.

**Comment by WendyKoelfgen** [comment]
Great to see some of the fields turn red when bad content is included. I struggled to know where I went wrong in the review process. You know which section but not what the mistake was. I went back several times and in the end I think it was an invalid address. Is that right? Is there address validation? Can that section turn red if its invalid?

2.5C - values are still starting at 1

**Comment by WendyKoelfgen** [comment]
The delete on 3.4 is because its redundant with the provided field

**Comment by CadyLister** [comment]
Save and continue button section 1 not working today

**Comment by derekwmiller** [comment]
@WendyKoelfgen The delete on 3.4 is because its redundant with the provided field

- I thought it was an either / or?

**Comment by WendyKoelfgen** [comment]
It's the exact same thing. 1-2 paragraphs about each team member. We already give them a field to paste it into. No need for an upload of the exact same content.

**Comment by derekwmiller** [comment]
Right. I understand that. I had assumed that you wanted to allow users who already had that info in a document the ability to upload it in place of cutting and pasting into that text box. Fine to remove.
