### ISSUE TITLE
Large grant review 9.21.20

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#76]
1.2 - Upload instruction text says “Attach the contract defining the fiscal sponsor agreement. Upload this file in Section 7: Accompanying documents.” Change to say “If you have a contract defining the fiscal sponsor agreement please upload this file in Section 7: Accompanying documents”

2.6 – can we do the hover text like in Planning 2.5? this question should be made optional for people applying with a fiscal sponsor

3.2 and 3.3 – percent values (2nd entry in each) should have max value of 100
Can’t change answer on 6.1 once you select it (yes or no)

6.4 – answering yes does not block answering rest of 6.4 and 6.5 per skip instructions
Section 6 skips don’t seem to be working and that gets in the way of review and submit. If I select the option in 6.2 that directs me to fill out section A, Section B is still open. If I select the option that directs me to fill out section B, section A is still available.

**Comment by WendyKoelfgen** [comment]
You can change the answer on 6.1 if you pick yes first. If you pick no, you cannot change your answer. Also can't save and continue after selecting no. 

I have completed a large application and cannot get past application review. Cannot figure out what my error might be. Section 1 is highlighted in the review and I have gone through and ensured valid/eligible responses.

**Comment by WendyKoelfgen** [comment]
Also, I think 2.9 needs to allow for zero on revenue and expenses. Some of these orgs are entirely volunteer and may have no cash moving for a particular year of operations.

**Comment by WendyKoelfgen** [comment]
I am super stuck. I cannot figure out what is wrong in the red sections (1,2 and 6). I can't tell what I did wrong. I keep making changes and saving and trying again and I cannot get to an approved application.

**Comment by WendyKoelfgen** [comment]
On 6.2 - if you fill in the wrong section A or B, does that produce an error? If so, there is no way to unselect the radio buttons in the section that you were not supposed to fill in.

**Comment by WendyKoelfgen** [comment]
Seems that my issues were related to not replacing the example text. Can we eliminate example text?
