### ISSUE TITLE
Small grant review 9.21.20

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#77]
1.2 - Upload instruction text says “Attach the contract defining the fiscal sponsor agreement. Upload this file in Section 7: Accompanying documents.” Change to say “If you have a contract defining the fiscal sponsor agreement please upload this file in Section 7: Accompanying documents”

2.6 – can we do the hover text like in Planning 2.5? this question should be made optional for people applying with a fiscal sponsor

**Comment by WendyKoelfgen** [comment]
I may be having a caching issue but I still can't save section 1. I have tried control F5 several time but no dice.

Also, on the homepage, all applications that have been started today are showing as submitted even when they are not submitted. Both cady and I are having that same issue.

**Comment by WendyKoelfgen** [comment]
![image](https://user-images.githubusercontent.com/68038292/93917570-04a40580-fcc0-11ea-8f33-8f77018549de.png)

Checking to see if github will all screenshots to be pasted in here

**Comment by WendyKoelfgen** [comment]
Can't save/continue on section 6
