### ISSUE TITLE
all grant types - 2 relatively minor issues

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#78]
I am concerned that the example text will get left in if it is what people would put. e.g. in the address I just tabbed past b/c it said Portland already and I assumed that would stay but it stopped the review from being complete

It would be good to put some text in the upload section that says it takes a minute so be patient while it uploads

**Comment by derekwmiller** [comment]
placeholder text is gone

I'm not concerned with the upload speed at this point. There are too many variables in play to determine whether it's an actual issue.... VPN, dev server, etc. If the upload continues to be slow on the production site, we can revisit.
