### ISSUE TITLE
small grant

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#79]
I am stuck at Application Review. Here's what I did:

1) Completed application with intentional errors
2) Clicked "Review Application" - response was red on section 1, everything else stayed white
3) I went back and resolved errors in section 1
4) Tried to click review application again but nothing happening
5) I tried refreshing and closing out of the application and going back in

**Comment by derekwmiller** [comment]
@WendyKoelfgen 
I'll need to see it. And I'll need to check the db via the application id #.

**Comment by CadyLister** [comment]
same thing happened to me application 1076

**Comment by CadyLister** [comment]
doesnt seem to be saving the application title

**Comment by derekwmiller** [comment]
@CadyLister in your case, there's no data for 2.6 a / b / c and nothing for section 4

**Comment by derekwmiller** [comment]
saves the title fine for me. will need to see your steps to reproduce
