### ISSUE TITLE
link to download packets

### ISSUE THREAD

**Issue by derekwmiller** [BPSTechServices/pcef-public#80]
I need a link (or links?) to the download packets. Yes, users should have these documents prior to submitting their application, but there's is no link from the application to download the required attachments. 

There are links to the guide. But,  honestly, I cannot find the link to the downloads from the guide.

**Comment by derekwmiller** [comment]
@CadyLister @WendyKoelfgen thoughts?

**Comment by CadyLister** [comment]
These are links to the application packet, they could go into the Help section but am open to ideas if you have some.

Planning grant material - https://hcpaw.portlandoregon.gov/userportal/#/shared/public/xUGh_xVBofnXQaH_/PCEF_Planning_Grant_Materials

Small grant material - https://hcpaw.portlandoregon.gov/userportal/#/shared/public/zEX9zxxF_cjeRf3P/PCEF_Small_Grant_Materials

Large grant material - https://hcpaw.portlandoregon.gov/userportal/#/shared/public/7jOonD4zqJT8M6ic/PCEF_Large_Grant_Materials

**Comment by derekwmiller** [comment]
are they not accessible from the guide? how do users access those documents?

**Comment by WendyKoelfgen** [comment]
This is where they can access the guides on the website https://www.portland.gov/bps/cleanenergy/services/apply-pcef-grant

**Comment by WendyKoelfgen** [comment]
Each link Cady provide and available here https://www.portland.gov/bps/cleanenergy/services/apply-pcef-grant contains the application packets. The packets contain the application templates. We want applicants to download the full packet and review before completing the online app.

**Comment by derekwmiller** [comment]
yup. just didn't see the links in the guide.
