### ISSUE TITLE
small grant review 9.22.20

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#81]
The only thing I saw was that the application review still requires the fields in 2.6 to be complete even if the applicant is applying with a fiscal sponsor

**Comment by derekwmiller** [comment]
2.6 ... somehow I missed that. Didn't realize fiscal sponsor made this section unnecessary

**Comment by CadyLister** [comment]
it makes it optional, they should still be able to fill out if they can

**Comment by derekwmiller** [comment]
ok. so my understanding is that it only negates the need to validate the section if fiscal sponsor = yes... correct?

**Comment by CadyLister** [comment]
that is correct

**Comment by derekwmiller** [comment]
cool. planning grant as well I'm guessing?

**Comment by CadyLister** [comment]
Planning grant doesn't have this section. Hey, also does JoEllen need a link or anything to be able to make the button live?

**Comment by derekwmiller** [comment]
planning grant does have this section

**Comment by derekwmiller** [comment]
and yes, JoEllen will need a link

**Comment by CadyLister** [comment]
oh my gosh Derek, you are correct. I was multi tasking poorly. Yes it is the same for planning as small and large when applying with a fiscal sponsor.

**Comment by CadyLister** [comment]
Can you send her/me the link so she can turn on the button tomorrow morning?

**Comment by derekwmiller** [comment]
yes. I'm working on the 'skip pattern on load' issue (section A / B etc). I'll send the link once that's resolved

**Comment by CadyLister** [comment]
Great, thank you!

Sent from my iPhone

On Sep 22, 2020, at 8:45 PM, derek miller <notifications@github.com> wrote:

﻿

yes. I'm working on the 'skip pattern on load' issue (section A / B etc). I'll send the link once that's resolved
