### ISSUE TITLE
large grant application review 9.22.20

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#82]
application review still requires the fields in 2.6 to be complete even if the applicant is applying with a fiscal sponsor

Section 6 - something wonky is going on where if you choose to fill out section A it looks like you cannot do section B which is correct, but then when you save and continue and then go back to section 6, all of section B appears editable and the review looks like there is an issue with section 6. When I select option to fill out section B the save and continue button does not work

**Comment by derekwmiller** [comment]
2.6 ... somehow I missed that. Didn't realize fiscal sponsor made this section unnecessary
