### ISSUE TITLE
Small grant skip patterns

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#83]
Section 1, 3, 4,5,6 = skip pattern working before and after saving and application review
Section 2 = 2.5 skip pattern not working, save and continue not working, when I clicked to section 3, no save message
Section 7 = uploads did not disappear after application review! Yes!

Everything seems cool except section 2

**Comment by derekwmiller** [comment]
2.5 works on a new form. Are you referring to a saved application?

**Comment by CadyLister** [comment]
just for clarification. Derek, when you say saved application I think what you mean is that you have hit save and continue on any section, is that correct?

**Comment by derekwmiller** [comment]
yes that's correct

if you look at the url... it will either say #/grant type/new/section number -- or -- #/grant type/application id/section number

the former is a new application (ie has never been saved). the latter is a saved application.

**Comment by CadyLister** [comment]
the skips do not work once the form has been saved

**Comment by CadyLister** [comment]
Just to get clarify. In a saved form: Section 2 skips do not work and save button does not work, Section 3 save button does not work. All else seems to be working but cannot test review submit b/c of the section 2 and 3 save issue

**Comment by derekwmiller** [comment]
@WendyKoelfgen  -- we took care of this yesterday evening, correct?

**Comment by WendyKoelfgen** [comment]
yep
