### ISSUE TITLE
large grant

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#85]
I went through a few different ways and it all worked except section 7 in the review gave me a green light even when I didn't upload anything.

**Comment by CadyLister** [comment]
ok, now I just tried again and section 7 seems to be working like it should

**Comment by derekwmiller** [comment]
@CadyLister -- @WendyKoelfgen has expressed similar issues. I have never been able to successfully replicate. The code that validates required files is very, very simple (unlike some of the sections). 

I'm not saying it didn't happen. But if it happens again, please share as much info as you can for replication.
