### ISSUE TITLE
Review criteria

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#90]
The list of review criteria for each grant type along with who reviews each (staff or review panel) are located here https://portlandoregongov.sharepoint.com/:x:/s/pcef/Ec3aI2n3b9BNguLkW1S3GT0BewEY7bZLVawe3kAsuHh0Qg?e=GuQIaf

The planning grant review criteria guidance is here https://portlandoregongov.sharepoint.com/:b:/s/pcef/EU-8Q-FzYFpGvnFwjCaXoVMBWTQ1QFlUY-shqb51BapGJA?e=U8SxO1

The small grant review criteria guidance is here https://portlandoregongov.sharepoint.com/:b:/s/pcef/EbZnMm7er2tGjl_1udkHR0oBaLmsoLpz3l-VQAGOskRa7w?e=7GXXfg

The large grant review criteria guidance is here https://portlandoregongov.sharepoint.com/:b:/s/pcef/EXmr77r60NFFn8jHmu1NHawBWpIH8qFChIKR-mBKv4EhAw?e=Ns9WbA

Each review panel will have 3 to 5 members

**Comment by WendyKoelfgen** [comment]
Technical review form link https://portlandoregongov.sharepoint.com/:x:/s/pcef/EQCf3vycv75Li0mGt_2wvEsBIxIAsZbAN9KORJ8PlzD87g?e=R47g71
