### ISSUE TITLE
Application review process

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#91]
1. Eligibility screening (performed by staff)
2. Technical review (performed by staff and other City SMEs)
3. Applications that pass #1 and #2 are sent to scoring panels, ~10 applications per panel, 5 people per panel, All members read all apps assigned to them. Each criteria will be scored on same Likert scale (math will need to adjust for final score based on point value of each criterion). Each panel member scores individually all relevant criteria, take notes and submit clarifying questions. 
4. Staff will average individual scores from each panelist and compile clarifying questions, send to applicant with response form template. Applicants are given a week to respond, response sent to scoring panel members. 
5. Scoring panel holds a meeting and has opportunity to discuss and change score, final individual scores are made, one final set of scores for each criterion is assigned (average of all individual). Scoring panel decides to recommend or not for funding, must provide rationale for not recommending for funding..
6. staff generates report for full committee consideration which includes summary info on each application recommended for funding consideration
7. Committee meeting(s) to make final recommendations to city council
8. City council approves recommended projects

**Comment by WendyKoelfgen** [comment]
Between 2 and 3, there could be a threshold review if we have more than 90 applications remaining. This will consist of staff doing an initial scoring of applications and potentially eliminating select applications from further consideration based on the outcome. Not sure how to keep that distinct from scoring panel scoring.
