### ISSUE TITLE
Planning grant - June review

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#94]
Section 4: Accompanying documents – the section doesn’t turn green if there aren’t two documents for 2.8. I just think there’s potential for someone to merge the documents together.

**Comment by derekwmiller** [comment]
So what’s the ask?

**Comment by CadyLister** [comment]
Allow one document to meet the document requirement for 2.8 (this issue is likely also present for small and large but i havent checked yet)
