### ISSUE TITLE
Reports and Charts

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#96]
- [x] Did not pass technical review

- [x] Did not pass eligibility review

- [x] Funds requested by grant type

- [x] Funds requested by project type

- [x] All fields all applications

- [x] Scored applications

- [x] Recommended applications

- [x] Not recommended applications

- [x] Total non-profit applicants

- [x] Total applications received

- [x] Number of applications by category (clean energy, regen ag, etc.)

- [x] Number of applications by grant type (planning, small, large)

- [x] General types of projects in each category

- [x] Range of funding requests

- [x] Threshold review scores
![image](https://user-images.githubusercontent.com/68038292/98406026-164c2d00-2022-11eb-8b33-6bc3f87dee60.png)

**Comment by WendyKoelfgen** [comment]
@derekwmiller Let me know if the screenshot is not useful. I can try to get the information in here a different way.

**Comment by derekwmiller** [comment]
screenshot is fine. thanks.

**Comment by WendyKoelfgen** [comment]
Just noting for later that we plan to address the need for creating application packets for the committee, incorporating select fields from select applications into a full report. Needed by 2/5/21.
